apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-app1
  labels:
    app: nginx
spec:
  replicas: 500
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodetype
                operator: In
                values:
                - pool1
                - pool2
                - pool4
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 80
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-spot
                operator: DoesNotExist

      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      priorityClassName: low-priority-apps
